"""empty message

Revision ID: 0782b10eace0
Revises: 
Create Date: 2017-01-03 14:43:29.865992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0782b10eace0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('university_ranking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('world_rank', sa.Integer(), nullable=True),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('national_rank', sa.Integer(), nullable=True),
    sa.Column('quality_of_education', sa.Integer(), nullable=True),
    sa.Column('alumni_employment', sa.Integer(), nullable=True),
    sa.Column('quality_of_faculty', sa.Integer(), nullable=True),
    sa.Column('publications', sa.Integer(), nullable=True),
    sa.Column('influence', sa.Integer(), nullable=True),
    sa.Column('citations', sa.Integer(), nullable=True),
    sa.Column('broad_impact', sa.Integer(), nullable=True),
    sa.Column('patents', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('university_ranking')
    # ### end Alembic commands ###
